#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "gcc -DOPENSSL_THREADS  -DDSO_WIN32 -mno-cygwin -DL_ENDIAN -DWIN32_LEAN_AND_MEAN -fomit-frame-pointer -O3 -march=i486 -Wall -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DWHIRLPOOL_ASM"
  #define PLATFORM "mingw"
  #define DATE "Thu Feb 11 21:18:41     2010"
#endif
